# Dockerfile.api
FROM python:3.9-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy everything (including data/, model/, main.py, etc)
COPY . .

EXPOSE 8000

# point Uvicorn at main:app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
