# Dockerfile.etl
FROM python:3.9-slim
WORKDIR /app

# install only what ETL needs
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# bring in data/model/scripts
COPY data      data
COPY model     model
COPY scripts   scripts

# run ETL once and exit
CMD ["python", "scripts/etl.py"]
