# Dockerfile.api
FROM python:3.9-slim

WORKDIR /app

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy your data and model
COPY data    ./data
COPY model   ./model

# copy the FastAPI code
COPY api     ./api

# expose and run
ENV DATA_DIR="data"
EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
